Tolk.Web/Controllers/StandardBusinessDocumentController.cs
using DataTables.AspNet.Core;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System;
using System.Linq;
using System.Threading.Tasks;
using Tolk.BusinessLogic.Data;
using Tolk.BusinessLogic.Enums;
using Tolk.BusinessLogic.Helpers;
using Tolk.BusinessLogic.Services;
using Tolk.BusinessLogic.Utilities;
using Tolk.Web.Authorization;
using Tolk.Web.Helpers;
using Tolk.Web.Models;

namespace Tolk.Web.Controllers
{
    [Authorize(Policy = Policies.SystemOrApplicationOrCustomerCentralAdmin)]
    public class StandardBusinessDocumentController : Controller
    {
        private readonly TolkDbContext _dbContext;
        private readonly IAuthorizationService _authorizationService;
        private readonly TolkOptions _options;        
        private readonly StandardBusinessDocumentService _standardBusinessDocumentService;
        private readonly CacheService _cacheService;
        public StandardBusinessDocumentController(
            TolkDbContext dbContext,
            IAuthorizationService authorizationService,
            IOptions<TolkOptions> options,            
            CacheService cacheService,
            StandardBusinessDocumentService standardBusinessDocumentService
            )
        {
            _dbContext = dbContext;
            _authorizationService = authorizationService;
            _options = options?.Value;            
            _cacheService = cacheService;
            _standardBusinessDocumentService = standardBusinessDocumentService;
        }

        public IActionResult List()
        {         
            if (!User.IsAppOrSysAdmin() && !_cacheService.CustomerSettings.Any(c => c.CustomerOrganisationId == User.TryGetCustomerOrganisationId() && c.UsedCustomerSettingTypes.Any(cs => cs == CustomerSettingType.UseOrderAgreements)))
            {
                return Forbid();
            }

            return View(new PeppolMessageListModel
            {
                FilterModel = new PeppolMessageFilterModel { 
                    IsAdmin = User.IsAppOrSysAdmin()
                }
            });
        }

        [HttpGet]
        public async Task<IActionResult> View(int id)
        {
            var peppolPayload = await _dbContext.PeppolPayloads.GetById(id);
            if (peppolPayload != null &&
                (await _authorizationService.AuthorizeAsync(User, peppolPayload, Policies.View)).Succeeded)
            {
                return View(PeppolMessageModel.GetModelFromPeppolPayload(peppolPayload, _options.EnableMockInvoice));
            }
            return Forbid();
        }
     
        [HttpGet]
        public async Task<ActionResult> GetPayload(int id)
        {
            var payload = await _dbContext.PeppolPayloads.GetById(id);
            if (payload != null && (await _authorizationService.AuthorizeAsync(User, payload, Policies.View)).Succeeded)
            {
                return File(payload.Payload, System.Net.Mime.MediaTypeNames.Application.Octet, $"{payload.PeppolMessageType}-{payload.IdentificationNumber}.xml");
            }
            return Forbid();
        }

        [HttpGet]
        public async Task<ActionResult> GetMockInvoiceForOrder(int id)
        {
            if (_options.EnableMockInvoice)
            {
                var request = await _dbContext.Requests.GetRequestForPeppolMessageCreation(id);
                var payload = await _standardBusinessDocumentService.CreateMockInvoiceFromRequest(request);
                if (payload != null && (await _authorizationService.AuthorizeAsync(User, payload, Policies.View)).Succeeded)
                {
                    return File(payload.Payload, System.Net.Mime.MediaTypeNames.Application.Octet, $"MOCKINVOICE-FOR-{request.Order.OrderNumber}.xml");
                }
            }
            return Forbid();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ListPeppolMessages(IDataTablesRequest request)
        {
            var model = new PeppolMessageFilterModel();
            await TryUpdateModelAsync(model);
            model.IsAdmin = User.IsAppOrSysAdmin();
            int? customerOrganisationId = !model.IsAdmin ? User.TryGetCustomerOrganisationId() : null;
            if(!model.IsAdmin && !customerOrganisationId.HasValue)
            {
                throw new InvalidOperationException($"{nameof(ListPeppolMessages)} User with ID: {User.GetUserId} is not linked to a customer organisation and is not a Sys- or  App Administrator");
            }
            var payloads = _dbContext.PeppolPayloads.ListOrderAgreements(customerOrganisationId);
            return AjaxDataTableHelper.GetData(request, payloads.Count(), model.Apply(payloads), x => x.Select(e =>
                    new PeppolMessageListItemModel
                    {
                        PeppolPayloadId = e.PeppolPayloadId,
                        IdentificationNumber = e.IdentificationNumber,                        
                        CreatedAt = e.CreatedAt,
                        OrderNumber = e.Request.Order.OrderNumber,
                        PeppolMessageType = e.PeppolMessageType.ToString(),
                        IsLatest = e.ReplacedById == null,                        
                        CustomerName = e.Request.Order.CustomerOrganisation.Name
                    }));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public JsonResult ListColumnDefinition()
        {
            var definition = AjaxDataTableHelper.GetColumnDefinitions<PeppolMessageListItemModel>().ToList();
            definition.Single(d => d.Name == nameof(PeppolMessageListItemModel.CustomerName)).Visible = User.IsAppOrSysAdmin();
            return Json(definition);
        }
    }
}

Tolk.Web/Views/StandardBusinessDocument/List.cshtml
@model PeppolMessageListModel
@using Tolk.Web.Services
@inject HelpLinkService HelpLinkService
@{
    ViewData["Title"] = "Peppol Messages";
    HelpLinkService.PageName = "admin-order-agreements/"; // Needs update
}
<section aria-label="@ViewData["Title"]">
    <h1>@ViewData["Title"] @HelpLinkService.HeaderAnchor()</h1>
    <div class="row filter-panel">
        @await Html.PartialAsync("_Filter", Model.FilterModel)
    </div>   
    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive ajax-listing table-datatable">
                <table class="table table-hover full-row-height clickable-rows-with-action search-table" data-order="[[ 3, &quot;desc&quot; ]]"
                       data-ajax-path="@Url.Action(nameof(Tolk.Web.Controllers.StandardBusinessDocumentController.ListPeppolMessages), "StandardBusinessDocument")"
                       data-ajax-column-definition="@Url.Action(nameof(Tolk.Web.Controllers.StandardBusinessDocumentController.ListColumnDefinition), "StandardBusinessDocument")"
                       data-click-action-url="@Url.Action(nameof(Tolk.Web.Controllers.StandardBusinessDocumentController.View), "StandardBusinessDocument")"
                       data-filter-selector=".filter-panel">
                </table>
            </div>
        </div>
    </div>
</section>

Tolk.Web/Views/StandardBusinessDocument/View.cshtml
@model PeppolMessageModel
@{
    ViewData["Title"] = "Order agreement";
}
<section aria-label="@ViewData["Title"]">
    <h1>@ViewData["Title"]</h1>
    <div class="row">
        <div class="col-sm-3">
            <display-entry asp-for="IdentificationNumber" />
        </div>
        <div class="col-sm-3">
            <display-entry asp-for="OrderNumber" />
        </div>
        <div class="col-sm-3">
            <display-entry asp-for="CreatedAt" />
        </div>
    </div>
    <div class="row">
        <div class="col-sm-3">
            <display-entry asp-for="IsLatest" />
        </div>
        <div class="col-sm-3">
            <display-entry asp-for="BasedOn" />
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <a asp-area="" asp-controller="StandardBusinessDocument" asp-action="GetPayload" asp-all-route-data="@(new Dictionary<string, string>{{ "id", Model.PeppolPayloadId.ToString() } })">Ladda ner filen</a><br />
        </div>
        @{
            if (Model.EnableMockInvoice)
            {             
                    <div class="col-sm-12">
                    <a asp-area="" asp-controller="StandardBusinessDocument" asp-action="GetMockInvoiceForOrder" asp-all-route-data="@(new Dictionary<string, string>{{ "id", Model.RequestId.ToString()} })">Ladda ner Mock-Faktura</a>
                    </div>
            }
        }
    </div>
    <div class="row">
        <div class="col-sm-12">
            <a class="btn btn-warning btn-large pull-left do-not-check-dirty" href="@Url.Action("List")"><span class="center-glyphicon glyphicon glyphicon-triangle-left"></span> Tillbaka</a>
        </div>
    </div>
</section>

Tolk.Web/Views/StandardBusinessDocument/_Filter.cshtml
@model PeppolMessageFilterModel
@inject SelectListService SelectListService
@using Tolk.Web.Services
<section aria-label="Filtrera">
    <div class="col-sm-12">
        <div class="row">
            <div class="col-xs-4">
                <h2>Filtrera</h2>
            </div>
            <div class="col-xs-8">
                <a class="btn btn-primary do-not-check-dirty reset-filter-button" href="@Url.Action("List")">Rensa filter <span class="btn-small-remove-times">&times;</span></a>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <form-entry asp-for="SearchIdentifier" />
            </div>
            @if (Model.IsAdmin)
            {
                <div class="col-sm-4">
                    <form-entry asp-for="CustomerOrganisationId" type="select" asp-items="SelectListService.CustomerOrganisations" class="allow-clear" />
                </div>
            }
            <div class="col-sm-4">
                <form-entry asp-for="IsLatest" type="select" asp-items="SelectListService.BoolList" class="allow-clear" />
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6">
                <form-entry asp-for="DateCreated" />
            </div>
        </div>
    </div>
</section>